(function(){
const LANG_KEY='gyirong-lang';
window.lang=localStorage.getItem(LANG_KEY)||((navigator.language||'zh').slice(0,2));
if(!(window.I18N&&I18N[window.lang])) window.lang='zh';
function t(k){return (I18N[window.lang]&&I18N[window.lang][k])||(I18N.zh&&I18N.zh[k])||k;}
function loc(v){if(v==null)return '';if(typeof v==='string')return v;return v[window.lang]||v.en||v.zh||Object.values(v)[0]||'';}
function stClass(s){return (s==='closed'||s==='blocked'||s==='destroyed')?'r':((s==='done'||s==='open'||s==='recovered')?'g':'a');}
function stLabel(s){const map={closed:{zh:'封闭',en:'Closed',ne:'बन्द',hi:'बंद'},limited:{zh:'受限',en:'Limited',ne:'सीमित',hi:'सीमित'},open:{zh:'可通',en:'Open',ne:'खुला',hi:'खुला'},done:{zh:'完成',en:'Done',ne:'भयो',hi:'हो गया'},staging:{zh:'集结',en:'Staging',ne:'जम्मा',hi:'एकत्र'},destroyed:{zh:'损毁',en:'Destroyed',ne:'भत्किए',hi:'नष्ट'}};
return loc(map[s]||{zh:s,en:s,ne:s,hi:s});}
function mergeSnap(snap){const D=window.GYIRONG_DATA||(window.GYIRONG_DATA={});if(!snap)return D;['kpi','roads','forces','sites','hydro','xPosts','timeline'].forEach(k=>{if(snap[k])D[k]=snap[k];});const incoming=snap.published||snap.items;if(incoming){D.published=D.published||[];incoming.forEach(it=>{if(!it.id)return;const i=D.published.findIndex(p=>p.id===it.id);if(i>=0)D.published[i]=it;else D.published.push(it);});}if(snap.snap)D.snap=snap.snap;return D;}
function bindBox(needle,id){let el=document.getElementById(id);if(el)return el;const heads=document.querySelectorAll('.side h3, aside h3');for(const h of heads){if((h.textContent||'').indexOf(needle)!==-1){const sec=h.nextElementSibling;if(sec&&sec.classList.contains('sec')){sec.id=id;return sec;}}}return null;}
function ensureBoxes(){bindBox('道路','roadsBox');bindBox('兵力','forcesBox');bindBox('救出','sitesBox');if(!document.getElementById('feedBox')){const side=document.querySelector('.side');if(side){const h=document.createElement('h3');h.setAttribute('data-i','feed');h.textContent=t('feed')||'动态';const box=document.createElement('div');box.className='sec';box.id='feedBox';box.style.maxHeight='220px';box.style.overflow='auto';const logH=Array.from(side.querySelectorAll('h3')).find(x=>x.textContent.indexOf('日志')!==-1);if(logH)side.insertBefore(h,logH);else side.appendChild(h);h.insertAdjacentElement('afterend',box);}}const lakeSec=document.querySelector('#lakeBox')||bindBox('堰塞湖','lakeBox');if(lakeSec&&!document.getElementById('lakeLive')){const live=document.createElement('div');live.id='lakeLive';live.className='row';lakeSec.appendChild(live);}}
function row(name,status,detail){return '<div class="pt">'+loc(name)+' <span class="st '+stClass(status)+'">'+(loc(detail)||stLabel(status))+'</span></div>';}
function renderChrome(){document.documentElement.lang=window.lang;document.querySelectorAll('[data-i]').forEach(el=>{el.textContent=t(el.dataset.i);});const D=window.GYIRONG_DATA||{};const k=D.kpi||{cn:{},np:{}};const top=document.querySelector('.topline');if(top){top.innerHTML='<div>CN <strong>'+(k.cn.dead??3)+' / '+(k.cn.missing??558)+' / '+(k.cn.rescued??2)+'</strong></div><div>NP <strong>'+(k.np.dead??469)+' / '+(k.np.missing??977)+'</strong></div><div>'+(D.snap?D.snap.replace('T',' ').slice(0,16):'')+' UTC</div>';}const bar=document.getElementById('langBar');const langs=window.LANGS||[{id:'zh',label:'中文'},{id:'en',label:'EN'},{id:'ne',label:'नेपाली'},{id:'hi',label:'हिन्दी'}];if(bar){bar.innerHTML=langs.map(L=>'<button data-lang="'+L.id+'" class="'+(L.id===window.lang?'on':'')+'">'+L.label+'</button>').join('');bar.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{window.lang=b.dataset.lang;localStorage.setItem(LANG_KEY,window.lang);renderAll();});}}
function renderLists(){ensureBoxes();const D=window.GYIRONG_DATA||{};const roads=document.getElementById('roadsBox');if(roads)roads.innerHTML=(D.roads||[]).map(r=>row(r.name,r.status,r.detail)).join('')||'<div class="pt">—</div>';const forces=document.getElementById('forcesBox');if(forces)forces.innerHTML=(D.forces||[]).map(r=>row(r.name,r.status,r.detail)).join('')||'<div class="pt">—</div>';const sites=document.getElementById('sitesBox');if(sites)sites.innerHTML=(D.sites||[]).map(r=>row(r.name,r.status,r.detail)).join('')||'<div class="pt">—</div>';const lake=document.getElementById('lakeLive');if(lake)lake.innerHTML=loc((D.hydro||{}).status);const feed=document.getElementById('feedBox');if(feed){const items=[...(D.published||[]),...(D.xPosts||[]).map(p=>({id:p.id,t:p.t,title:p.text||p.title,body:'',link:p.link,src:'x'}))].sort((a,b)=>new Date(b.t)-new Date(a.t)).slice(0,12);feed.innerHTML=items.map(p=>'<div class="pt" style="display:block"><div class="meta">'+(p.t||'').slice(0,16).replace('T',' ')+' · '+(p.src==='official'?t('official'):(p.src||''))+'</div><div>'+loc(p.title)+'</div><div class="meta">'+loc(p.body)+'</div>'+(p.link?'<a href="'+p.link+'" target="_blank" style="color:#8fd4f0;font-size:11px">link</a>':'')+'</div>').join('');}}
function plotNews(){if(typeof map==='undefined'||!map)return;window.newsMarks=window.newsMarks||[];window.newsMarks.forEach(m=>m.remove());window.newsMarks=[];const D=window.GYIRONG_DATA||{};[...(D.published||[]),...(D.xPosts||[])].forEach(p=>{if(p.lat==null||p.lng==null||p.geo==='unknown')return;const el=document.createElement('div');el.style.cssText='width:9px;height:9px;border-radius:50%;background:#d7b15a;border:1px solid #111';window.newsMarks.push(new maplibregl.Marker({element:el}).setLngLat([p.lng,p.lat]).setPopup(new maplibregl.Popup().setHTML('<div class="popup"><h4>'+loc(p.title||p.text)+'</h4><p>'+loc(p.body||'')+'</p></div>')).addTo(map));});}
async function pullSnapshot(){try{const r=await fetch('snapshot.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)return;mergeSnap(await r.json());renderAll();}catch(e){}}
function renderAll(){renderChrome();renderLists();plotNews();}
window.renderLive=renderAll;window.pullSnapshot=pullSnapshot;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){renderAll();pullSnapshot();});else{renderAll();pullSnapshot();}
setInterval(pullSnapshot,60000);
})();
