window.I18N={
zh:{title:'吉隆·Rasuwa COP',unofficial:'非官方 · 用户内容需审核',tabFeed:'动态',tabX:'X',tabSubmit:'上报',tabOps:'图层',feed:'动态',official:'官方',userOk:'用户',original:'原文',commentPh:'评论',submitH:'上报',submitWarn:'不要上传遇难者可辨认照片。',labelTitle:'标题',labelBody:'描述',submitBtn:'提交',needTitle:'必填',queued:'已入队',xH:'X',openPost:'原帖',
legendOpen:'可通行',legendLimited:'受限',legendClosed:'封闭',legendBorder:'国境',legendPath:'路径',layers:'图层',flyPort:'国门',flyLake:'堰塞湖',flyTown:'吉隆镇',flyWide:'全图',roadsForces:'道路 / 兵力',lakeTitle:'堰塞湖',phaseRecon:'侦察',phaseApproach:'前突',phaseSearch:'搜救',phaseWithdraw:'避险',footerNote:'坐标来自报道，不是实时北斗。',layer3d:'3D',layerC:'等高线',layerBd:'国境',layerRd:'道路',layerLake:'堰塞湖',layerPath:'路径'},
en:{title:'Gyirong · Rasuwa COP',unofficial:'Unofficial',tabFeed:'Feed',tabX:'X',tabSubmit:'Report',tabOps:'Layers',feed:'Feed',official:'Official',userOk:'User',original:'Source',commentPh:'Comment',submitH:'Report',submitWarn:'No identifiable victim photos.',labelTitle:'Title',labelBody:'Body',submitBtn:'Submit',needTitle:'Required',queued:'Queued',xH:'X',openPost:'Post',
legendOpen:'Open',legendLimited:'Limited',legendClosed:'Closed',legendBorder:'Border',legendPath:'Path',layers:'Layers',flyPort:'Gate',flyLake:'Lake',flyTown:'Town',flyWide:'Wide',roadsForces:'Roads / forces',lakeTitle:'Barrier lake',phaseRecon:'Recon',phaseApproach:'Push',phaseSearch:'Search',phaseWithdraw:'Hold',footerNote:'Pins are reported locations, not live GNSS.',layer3d:'3D',layerC:'Contours',layerBd:'Border',layerRd:'Roads',layerLake:'Lake',layerPath:'Path'},
ne:{title:'ग्यिरोङ COP',unofficial:'अनौपचारिक',tabFeed:'फिड',tabX:'X',tabSubmit:'रिपोर्ट',tabOps:'तह',feed:'फिड',official:'आधिकारिक',userOk:'नागरिक',original:'मूल',commentPh:'टिप्पणी',submitH:'रिपोर्ट',submitWarn:'पीडित फोटो नराख्नुहोस्।',labelTitle:'शीर्षक',labelBody:'विवरण',submitBtn:'पठाउनुहोस्',needTitle:'आवश्यक',queued:'कतार',xH:'X',openPost:'पोस्ट',
legendOpen:'खुला',legendLimited:'सीमित',legendClosed:'बन्द',legendBorder:'सीमा',legendPath:'मार्ग',layers:'तह',flyPort:'द्वार',flyLake:'ताल',flyTown:'सहर',flyWide:'पूर्ण',roadsForces:'सडक / बल',lakeTitle:'ताल',phaseRecon:'निरीक्षण',phaseApproach:'अगाडि',phaseSearch:'खोज',phaseWithdraw:'रोक',footerNote:'पिन रिपोर्ट स्थान हुन्।',layer3d:'3D',layerC:'कन्टुर',layerBd:'सीमा',layerRd:'सडक',layerLake:'ताल',layerPath:'मार्ग'},
hi:{title:'ग्यिरोंग COP',unofficial:'अनौपचारिक',tabFeed:'फ़ीड',tabX:'X',tabSubmit:'रिपोर्ट',tabOps:'परत',feed:'फ़ीड',official:'आधिकारिक',userOk:'उपयोगकर्ता',original:'मूल',commentPh:'टिप्पणी',submitH:'रिपोर्ट',submitWarn:'पीड़ित फोटो न डालें।',labelTitle:'शीर्षक',labelBody:'विवरण',submitBtn:'भेजें',needTitle:'ज़रूरी',queued:'कतार',xH:'X',openPost:'पोस्ट',
legendOpen:'खुला',legendLimited:'सीमित',legendClosed:'बंद',legendBorder:'सीमा',legendPath:'मार्ग',layers:'परत',flyPort:'द्वार',flyLake:'झील',flyTown:'नगर',flyWide:'पूरा',roadsForces:'सड़क / बल',lakeTitle:'झील',phaseRecon:'पैमाइश',phaseApproach:'आगे',phaseSearch:'खोज',phaseWithdraw:'रोक',footerNote:'पिन रिपोर्ट स्थान हैं।',layer3d:'3D',layerC:'समोच्च',layerBd:'सीमा',layerRd:'सड़क',layerLake:'झील',layerPath:'मार्ग'}
};
window.LANGS=[{id:'zh',label:'中文'},{id:'en',label:'EN'},{id:'ne',label:'नेपाली'},{id:'hi',label:'हिन्दी'}];
